name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -tt -o StrictHostKeyChecking=no ubuntu@ec2-3-147-205-221.us-east-2.compute.amazonaws.com << EOF
        git clone https://github.com/Tsaranya86/ClumsyBird.git
        cd ClumsyBird
        git pull origin main
        sudo npm install -g grunt-cli pm2
        cd /home/ubuntu/ClumsyBird
        npm install
        pm2 start grunt --name "ClumsyBird"        
        EOF
