name: CI/CD Workflow

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
            npm install -g grunt-cli
            npm install
  
      - name: Build the project
        run: |
            grunt clean --force
            grunt build --force
            grunt

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Main Branch
        run: |
          git config --global user.email "saranya.t86@gmail.com"
          git config --global user.name "Sara T"
          
          # Fetch all branches and switch to main
          git fetch
          git checkout main

          # Merge develop into main
          git merge develop --no-ff -m "Deploying from develop to main"

          # Push changes to main
          git push origin main


          

