name: Deploy to S3
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    # Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3
 
    # Set up AWS credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AKIAV7OAZA6UK5UTC2HZ }}
        aws-secret-access-key: ${{ secrets.tnKpkQsCytwfHAZWQHR2Qf+NGEQnzo4rrP0FWs0x }}
        aws-region: us-east-1
 
   
 
    # Sync build output to S3
    - name: Upload to S3
      run: |
        aws s3 sync ./build/ s3://clumsybirddbu --delete
