name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install -g grunt-cli
          npm install

      - name: Build the project
        run: |
          grunt clean --force
          grunt build --force
          grunt

      - name: Debug: Verify Build Directory
        run: ls -al ./build || { echo "Build directory not found"; exit 1; }

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: us-east-2

      - name: 
        Debug: Verify Build Directory Before Deployment
        run: ls -al ./build

      - name: Upload to S3
        run: |
          aws s3 sync ./build/ s3://clumsybirddbu/build
