name: NodeJS with Grunt and Version History

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install -g grunt-cli
          npm install grunt-contrib-copy --save-dev
          npm install

      - name: Build the project
        run: |
          grunt clean --force
          grunt build --force
          grunt
                    
      - name: Upload Build Directory
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./build

      - name: Increment Version
        run: |
          git config user.name "Tsaranya86"
          git config user.email "saranya.t86@gmail.com"
          git status
          if [ -n "$(git status --porcelain)" ]; then
            git add build/clumsy-min.js
            git add package-lock.json
            git add package.json
            git add build/index.html
            git commit -m "chore: Save changes before version bump" || echo "No changes to commit"
          fi 
          npm version patch -m "chore(release): %s"
          VERSION=$(node -p "require('./package.json').version")
          git tag v$VERSION
          git push origin main
          git push origin --tags
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Build Directory
        uses: actions/download-artifact@v4
        with:
           name: build
           

      - name: Show Current Directory
        run: pwd

      - name: List Files in Current Directory
        run: ls -al /home/runner/work/ClumsyBird/ClumsyBird
           
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: us-east-2

      - name: Upload to S3
        run: |
          aws s3 sync /home/runner/work/ClumsyBird/ClumsyBird/ s3://clumsybirddbu/build
          aws s3 cp /home/runner/work/ClumsyBird/ClumsyBird/index.html s3://clumsybirddbu
